url: https://jaselchauhan.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Jasel Chauhan
email: jasel.chauhan@gmail.com
description: "full stack web developer | teacher | tech enthusiast"


# Team names, titles and social links
people:
- name: Jasel Chauhan
  pic: 1
  position: Web Developer - Full Stack
  social:
    - title: twitter
      url: #
    - title: github
      url: #
    - title: stack-overflow
      url: #



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jaselchauhan
  - title: linkedin
    url: https://uk.linkedin.com/in/jaselchauhan
  - title: twitter
    url: http://twitter.com/_jaselchauhan
  - title: stack-overflow
    url: http://stackoverflow.com/users/5730970/function-declared
  - title: envelope
    url: mailto:jasel.chauhan@gmail.com


# Postal address (add as many lines as necessary)
address:
  - line: London

# Build settings
markdown: kramdown
permalink: pretty
theme: scribble
